#!/bin/bash
echo "🔍 Agent Builder Platform Status"
echo "================================="
echo ""
echo "API (Port 8000):"
lsof -i :8000 | grep LISTEN && echo "✅ Running" || echo "❌ Not running"
echo ""
echo "Admin Dashboard (Port 3000):"
lsof -i :3000 | grep LISTEN && echo "✅ Running" || echo "❌ Not running"
echo ""
echo "Widget (Port 5173):"
lsof -i :5173 | grep LISTEN && echo "✅ Running" || echo "❌ Not running"
echo ""
echo "================================="
echo "📍 Service URLs:"
echo "   API:              http://localhost:8000"
echo "   API Docs:         http://localhost:8000/docs"
echo "   Admin Dashboard:  http://localhost:3000"
echo "   Widget Demo:      http://localhost:5173"
